### PR TITLE
Parallel computegallery versions

### PR DESCRIPTION
**Pull request by Hanse00**
I believe these changes should address the comments in #12.

I am using my own fork to complete a migration of images between tenants right now, once I confirm that it worked as intended. I will mark this as ready.

### CODE REVIEW

**Comment by Hanse00** [comment]
@jamasten Would you like me to bump the version and modification dates in the scripts as well?

**Comment by jamasten** [comment]
@Hanse00 Yes, please update the version numbers and modification dates. Also, under the "Author" line, please add "Contributors" with your name next to it. Thanks!

**Comment by Hanse00** [comment]
@jamasten I believe this is ready for your review whenever you have a chance.

**Comment by Hanse00** [comment]
Hey @jamasten - I wanted to add another change, but want to check in with you first about whether it makes sense, and if so whether you'd prefer I add it to this PR or create a separate one: It would be great for the local directory where the VHD files are stored to be configurable, so that one can download images that don't necessarily fit in the user's downloads directory. What do you think?

**Review by jamasten — APPROVED** [review]

**Pull request merged**
